'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSPSA5
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PersonaServiceA5SoapBinding", [Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class PersonaServiceA5
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getPersonaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getPersonaListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private dummyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SocCam_Mantenimiento.My.MySettings.Default.SocCam_Mantenimiento_WSPSA5_PersonaServiceA5
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getPersonaCompleted As getPersonaCompletedEventHandler
        
        '''<remarks/>
        Public Event getPersonaListCompleted As getPersonaListCompletedEventHandler
        
        '''<remarks/>
        Public Event dummyCompleted As dummyCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://a5.soap.ws.server.puc.sr/", ResponseNamespace:="http://a5.soap.ws.server.puc.sr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getPersona(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal token As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal sign As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal cuitRepresentada As Long, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idPersona As Long) As <System.Xml.Serialization.XmlElementAttribute("personaReturn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> personaReturn
            Dim results() As Object = Me.Invoke("getPersona", New Object() {token, sign, cuitRepresentada, idPersona})
            Return CType(results(0),personaReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getPersonaAsync(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona As Long)
            Me.getPersonaAsync(token, sign, cuitRepresentada, idPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getPersonaAsync(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona As Long, ByVal userState As Object)
            If (Me.getPersonaOperationCompleted Is Nothing) Then
                Me.getPersonaOperationCompleted = AddressOf Me.OngetPersonaOperationCompleted
            End If
            Me.InvokeAsync("getPersona", New Object() {token, sign, cuitRepresentada, idPersona}, Me.getPersonaOperationCompleted, userState)
        End Sub
        
        Private Sub OngetPersonaOperationCompleted(ByVal arg As Object)
            If (Not (Me.getPersonaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getPersonaCompleted(Me, New getPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://a5.soap.ws.server.puc.sr/", ResponseNamespace:="http://a5.soap.ws.server.puc.sr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getPersonaList(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal token As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal sign As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal cuitRepresentada As Long, <System.Xml.Serialization.XmlElementAttribute("idPersona", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idPersona() As Long) As <System.Xml.Serialization.XmlElementAttribute("personaListReturn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> personaListReturn
            Dim results() As Object = Me.Invoke("getPersonaList", New Object() {token, sign, cuitRepresentada, idPersona})
            Return CType(results(0),personaListReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getPersonaListAsync(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona() As Long)
            Me.getPersonaListAsync(token, sign, cuitRepresentada, idPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getPersonaListAsync(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona() As Long, ByVal userState As Object)
            If (Me.getPersonaListOperationCompleted Is Nothing) Then
                Me.getPersonaListOperationCompleted = AddressOf Me.OngetPersonaListOperationCompleted
            End If
            Me.InvokeAsync("getPersonaList", New Object() {token, sign, cuitRepresentada, idPersona}, Me.getPersonaListOperationCompleted, userState)
        End Sub
        
        Private Sub OngetPersonaListOperationCompleted(ByVal arg As Object)
            If (Not (Me.getPersonaListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getPersonaListCompleted(Me, New getPersonaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://a5.soap.ws.server.puc.sr/", ResponseNamespace:="http://a5.soap.ws.server.puc.sr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dummy() As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> dummyReturn
            Dim results() As Object = Me.Invoke("dummy", New Object(-1) {})
            Return CType(results(0),dummyReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub dummyAsync()
            Me.dummyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub dummyAsync(ByVal userState As Object)
            If (Me.dummyOperationCompleted Is Nothing) Then
                Me.dummyOperationCompleted = AddressOf Me.OndummyOperationCompleted
            End If
            Me.InvokeAsync("dummy", New Object(-1) {}, Me.dummyOperationCompleted, userState)
        End Sub
        
        Private Sub OndummyOperationCompleted(ByVal arg As Object)
            If (Not (Me.dummyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent dummyCompleted(Me, New dummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class personaReturn
        
        Private datosGeneralesField As datosGenerales
        
        Private datosMonotributoField As datosMonotributo
        
        Private datosRegimenGeneralField As datosRegimenGeneral
        
        Private errorConstanciaField As errorConstancia
        
        Private errorMonotributoField As errorMonotributo
        
        Private errorRegimenGeneralField As errorRegimenGeneral
        
        Private metadataField As metadata
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datosGenerales() As datosGenerales
            Get
                Return Me.datosGeneralesField
            End Get
            Set
                Me.datosGeneralesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datosMonotributo() As datosMonotributo
            Get
                Return Me.datosMonotributoField
            End Get
            Set
                Me.datosMonotributoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datosRegimenGeneral() As datosRegimenGeneral
            Get
                Return Me.datosRegimenGeneralField
            End Get
            Set
                Me.datosRegimenGeneralField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorConstancia() As errorConstancia
            Get
                Return Me.errorConstanciaField
            End Get
            Set
                Me.errorConstanciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorMonotributo() As errorMonotributo
            Get
                Return Me.errorMonotributoField
            End Get
            Set
                Me.errorMonotributoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorRegimenGeneral() As errorRegimenGeneral
            Get
                Return Me.errorRegimenGeneralField
            End Get
            Set
                Me.errorRegimenGeneralField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property metadata() As metadata
            Get
                Return Me.metadataField
            End Get
            Set
                Me.metadataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class datosGenerales
        
        Private apellidoField As String
        
        Private dependenciaField As dependencia
        
        Private domicilioFiscalField As domicilio
        
        Private estadoClaveField As String
        
        Private fechaContratoSocialField As Date
        
        Private fechaContratoSocialFieldSpecified As Boolean
        
        Private idPersonaField As Long
        
        Private idPersonaFieldSpecified As Boolean
        
        Private mesCierreField As Integer
        
        Private mesCierreFieldSpecified As Boolean
        
        Private nombreField As String
        
        Private razonSocialField As String
        
        Private tipoClaveField As String
        
        Private tipoPersonaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dependencia() As dependencia
            Get
                Return Me.dependenciaField
            End Get
            Set
                Me.dependenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property domicilioFiscal() As domicilio
            Get
                Return Me.domicilioFiscalField
            End Get
            Set
                Me.domicilioFiscalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estadoClave() As String
            Get
                Return Me.estadoClaveField
            End Get
            Set
                Me.estadoClaveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaContratoSocial() As Date
            Get
                Return Me.fechaContratoSocialField
            End Get
            Set
                Me.fechaContratoSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaContratoSocialSpecified() As Boolean
            Get
                Return Me.fechaContratoSocialFieldSpecified
            End Get
            Set
                Me.fechaContratoSocialFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idPersona() As Long
            Get
                Return Me.idPersonaField
            End Get
            Set
                Me.idPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaSpecified() As Boolean
            Get
                Return Me.idPersonaFieldSpecified
            End Get
            Set
                Me.idPersonaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mesCierre() As Integer
            Get
                Return Me.mesCierreField
            End Get
            Set
                Me.mesCierreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property mesCierreSpecified() As Boolean
            Get
                Return Me.mesCierreFieldSpecified
            End Get
            Set
                Me.mesCierreFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property razonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoClave() As String
            Get
                Return Me.tipoClaveField
            End Get
            Set
                Me.tipoClaveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoPersona() As String
            Get
                Return Me.tipoPersonaField
            End Get
            Set
                Me.tipoPersonaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class dependencia
        
        Private codPostalField As String
        
        Private descripcionDependenciaField As String
        
        Private descripcionProvinciaField As String
        
        Private direccionField As String
        
        Private idDependenciaField As Integer
        
        Private idDependenciaFieldSpecified As Boolean
        
        Private idProvinciaField As Integer
        
        Private idProvinciaFieldSpecified As Boolean
        
        Private localidadField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codPostal() As String
            Get
                Return Me.codPostalField
            End Get
            Set
                Me.codPostalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionDependencia() As String
            Get
                Return Me.descripcionDependenciaField
            End Get
            Set
                Me.descripcionDependenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionProvincia() As String
            Get
                Return Me.descripcionProvinciaField
            End Get
            Set
                Me.descripcionProvinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idDependencia() As Integer
            Get
                Return Me.idDependenciaField
            End Get
            Set
                Me.idDependenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idDependenciaSpecified() As Boolean
            Get
                Return Me.idDependenciaFieldSpecified
            End Get
            Set
                Me.idDependenciaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idProvincia() As Integer
            Get
                Return Me.idProvinciaField
            End Get
            Set
                Me.idProvinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idProvinciaSpecified() As Boolean
            Get
                Return Me.idProvinciaFieldSpecified
            End Get
            Set
                Me.idProvinciaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class dummyReturn
        
        Private appserverField As String
        
        Private authserverField As String
        
        Private dbserverField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property appserver() As String
            Get
                Return Me.appserverField
            End Get
            Set
                Me.appserverField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property authserver() As String
            Get
                Return Me.authserverField
            End Get
            Set
                Me.authserverField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dbserver() As String
            Get
                Return Me.dbserverField
            End Get
            Set
                Me.dbserverField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class persona
        
        Private datosGeneralesField As datosGenerales
        
        Private datosMonotributoField As datosMonotributo
        
        Private datosRegimenGeneralField As datosRegimenGeneral
        
        Private errorConstanciaField As errorConstancia
        
        Private errorMonotributoField As errorMonotributo
        
        Private errorRegimenGeneralField As errorRegimenGeneral
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datosGenerales() As datosGenerales
            Get
                Return Me.datosGeneralesField
            End Get
            Set
                Me.datosGeneralesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datosMonotributo() As datosMonotributo
            Get
                Return Me.datosMonotributoField
            End Get
            Set
                Me.datosMonotributoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datosRegimenGeneral() As datosRegimenGeneral
            Get
                Return Me.datosRegimenGeneralField
            End Get
            Set
                Me.datosRegimenGeneralField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorConstancia() As errorConstancia
            Get
                Return Me.errorConstanciaField
            End Get
            Set
                Me.errorConstanciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorMonotributo() As errorMonotributo
            Get
                Return Me.errorMonotributoField
            End Get
            Set
                Me.errorMonotributoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorRegimenGeneral() As errorRegimenGeneral
            Get
                Return Me.errorRegimenGeneralField
            End Get
            Set
                Me.errorRegimenGeneralField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class datosMonotributo
        
        Private actividadMonotributistaField As actividad
        
        Private categoriaMonotributoField As categoria
        
        Private componenteDeSociedadField() As relacion
        
        Private impuestoField() As impuesto
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property actividadMonotributista() As actividad
            Get
                Return Me.actividadMonotributistaField
            End Get
            Set
                Me.actividadMonotributistaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property categoriaMonotributo() As categoria
            Get
                Return Me.categoriaMonotributoField
            End Get
            Set
                Me.categoriaMonotributoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("componenteDeSociedad", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property componenteDeSociedad() As relacion()
            Get
                Return Me.componenteDeSociedadField
            End Get
            Set
                Me.componenteDeSociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("impuesto", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property impuesto() As impuesto()
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class actividad
        
        Private descripcionActividadField As String
        
        Private idActividadField As Long
        
        Private idActividadFieldSpecified As Boolean
        
        Private nomencladorField As Integer
        
        Private nomencladorFieldSpecified As Boolean
        
        Private ordenField As Integer
        
        Private ordenFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionActividad() As String
            Get
                Return Me.descripcionActividadField
            End Get
            Set
                Me.descripcionActividadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idActividad() As Long
            Get
                Return Me.idActividadField
            End Get
            Set
                Me.idActividadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idActividadSpecified() As Boolean
            Get
                Return Me.idActividadFieldSpecified
            End Get
            Set
                Me.idActividadFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nomenclador() As Integer
            Get
                Return Me.nomencladorField
            End Get
            Set
                Me.nomencladorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property nomencladorSpecified() As Boolean
            Get
                Return Me.nomencladorFieldSpecified
            End Get
            Set
                Me.nomencladorFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property orden() As Integer
            Get
                Return Me.ordenField
            End Get
            Set
                Me.ordenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ordenSpecified() As Boolean
            Get
                Return Me.ordenFieldSpecified
            End Get
            Set
                Me.ordenFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class categoria
        
        Private descripcionCategoriaField As String
        
        Private idCategoriaField As Integer
        
        Private idCategoriaFieldSpecified As Boolean
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionCategoria() As String
            Get
                Return Me.descripcionCategoriaField
            End Get
            Set
                Me.descripcionCategoriaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idCategoria() As Integer
            Get
                Return Me.idCategoriaField
            End Get
            Set
                Me.idCategoriaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idCategoriaSpecified() As Boolean
            Get
                Return Me.idCategoriaFieldSpecified
            End Get
            Set
                Me.idCategoriaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class relacion
        
        Private apellidoPersonaAsociadaField As String
        
        Private ffRelacionField As Date
        
        Private ffRelacionFieldSpecified As Boolean
        
        Private ffVencimientoField As Date
        
        Private ffVencimientoFieldSpecified As Boolean
        
        Private idPersonaAsociadaField As Long
        
        Private idPersonaAsociadaFieldSpecified As Boolean
        
        Private nombrePersonaAsociadaField As String
        
        Private razonSocialPersonaAsociadaField As String
        
        Private tipoComponenteField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property apellidoPersonaAsociada() As String
            Get
                Return Me.apellidoPersonaAsociadaField
            End Get
            Set
                Me.apellidoPersonaAsociadaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ffRelacion() As Date
            Get
                Return Me.ffRelacionField
            End Get
            Set
                Me.ffRelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffRelacionSpecified() As Boolean
            Get
                Return Me.ffRelacionFieldSpecified
            End Get
            Set
                Me.ffRelacionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ffVencimiento() As Date
            Get
                Return Me.ffVencimientoField
            End Get
            Set
                Me.ffVencimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffVencimientoSpecified() As Boolean
            Get
                Return Me.ffVencimientoFieldSpecified
            End Get
            Set
                Me.ffVencimientoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idPersonaAsociada() As Long
            Get
                Return Me.idPersonaAsociadaField
            End Get
            Set
                Me.idPersonaAsociadaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaAsociadaSpecified() As Boolean
            Get
                Return Me.idPersonaAsociadaFieldSpecified
            End Get
            Set
                Me.idPersonaAsociadaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombrePersonaAsociada() As String
            Get
                Return Me.nombrePersonaAsociadaField
            End Get
            Set
                Me.nombrePersonaAsociadaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property razonSocialPersonaAsociada() As String
            Get
                Return Me.razonSocialPersonaAsociadaField
            End Get
            Set
                Me.razonSocialPersonaAsociadaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoComponente() As String
            Get
                Return Me.tipoComponenteField
            End Get
            Set
                Me.tipoComponenteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class impuesto
        
        Private descripcionImpuestoField As String
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionImpuesto() As String
            Get
                Return Me.descripcionImpuestoField
            End Get
            Set
                Me.descripcionImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class datosRegimenGeneral
        
        Private actividadField() As actividad
        
        Private categoriaAutonomoField As categoria
        
        Private impuestoField() As impuesto
        
        Private regimenField() As regimen
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("actividad", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property actividad() As actividad()
            Get
                Return Me.actividadField
            End Get
            Set
                Me.actividadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property categoriaAutonomo() As categoria
            Get
                Return Me.categoriaAutonomoField
            End Get
            Set
                Me.categoriaAutonomoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("impuesto", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property impuesto() As impuesto()
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("regimen", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property regimen() As regimen()
            Get
                Return Me.regimenField
            End Get
            Set
                Me.regimenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class regimen
        
        Private descripcionRegimenField As String
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private idRegimenField As Integer
        
        Private idRegimenFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        Private tipoRegimenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionRegimen() As String
            Get
                Return Me.descripcionRegimenField
            End Get
            Set
                Me.descripcionRegimenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idRegimen() As Integer
            Get
                Return Me.idRegimenField
            End Get
            Set
                Me.idRegimenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idRegimenSpecified() As Boolean
            Get
                Return Me.idRegimenFieldSpecified
            End Get
            Set
                Me.idRegimenFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoRegimen() As String
            Get
                Return Me.tipoRegimenField
            End Get
            Set
                Me.tipoRegimenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class errorConstancia
        
        Private apellidoField As String
        
        Private errorField() As String
        
        Private idPersonaField As Long
        
        Private idPersonaFieldSpecified As Boolean
        
        Private nombreField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("error", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property [error]() As String()
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idPersona() As Long
            Get
                Return Me.idPersonaField
            End Get
            Set
                Me.idPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaSpecified() As Boolean
            Get
                Return Me.idPersonaFieldSpecified
            End Get
            Set
                Me.idPersonaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class errorMonotributo
        
        Private errorField() As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("error", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property [error]() As String()
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class errorRegimenGeneral
        
        Private errorField() As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("error", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property [error]() As String()
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class personaListReturn
        
        Private metadataField As metadata
        
        Private personaField() As persona
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property metadata() As metadata
            Get
                Return Me.metadataField
            End Get
            Set
                Me.metadataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("persona", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property persona() As persona()
            Get
                Return Me.personaField
            End Get
            Set
                Me.personaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class metadata
        
        Private fechaHoraField As Date
        
        Private fechaHoraFieldSpecified As Boolean
        
        Private servidorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaHora() As Date
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaHoraSpecified() As Boolean
            Get
                Return Me.fechaHoraFieldSpecified
            End Get
            Set
                Me.fechaHoraFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property servidor() As String
            Get
                Return Me.servidorField
            End Get
            Set
                Me.servidorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a5.soap.ws.server.puc.sr/")>  _
    Partial Public Class domicilio
        
        Private codPostalField As String
        
        Private datoAdicionalField As String
        
        Private descripcionProvinciaField As String
        
        Private direccionField As String
        
        Private idProvinciaField As Integer
        
        Private idProvinciaFieldSpecified As Boolean
        
        Private localidadField As String
        
        Private tipoDatoAdicionalField As String
        
        Private tipoDomicilioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codPostal() As String
            Get
                Return Me.codPostalField
            End Get
            Set
                Me.codPostalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datoAdicional() As String
            Get
                Return Me.datoAdicionalField
            End Get
            Set
                Me.datoAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionProvincia() As String
            Get
                Return Me.descripcionProvinciaField
            End Get
            Set
                Me.descripcionProvinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idProvincia() As Integer
            Get
                Return Me.idProvinciaField
            End Get
            Set
                Me.idProvinciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idProvinciaSpecified() As Boolean
            Get
                Return Me.idProvinciaFieldSpecified
            End Get
            Set
                Me.idProvinciaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDatoAdicional() As String
            Get
                Return Me.tipoDatoAdicionalField
            End Get
            Set
                Me.tipoDatoAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDomicilio() As String
            Get
                Return Me.tipoDomicilioField
            End Get
            Set
                Me.tipoDomicilioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub getPersonaCompletedEventHandler(ByVal sender As Object, ByVal e As getPersonaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getPersonaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As personaReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),personaReturn)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub getPersonaListCompletedEventHandler(ByVal sender As Object, ByVal e As getPersonaListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getPersonaListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As personaListReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),personaListReturn)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub dummyCompletedEventHandler(ByVal sender As Object, ByVal e As dummyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class dummyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As dummyReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),dummyReturn)
            End Get
        End Property
    End Class
End Namespace
